### ISSUE TITLE
tlg0013.tlg002.perseus-grc1 needs to be in Perseids for treebanking

### ISSUE THREAD

**Issue by srdee** [PerseusDL/canonical#136]
Homer class

**Comment by balmas** [comment]
it's already there...

**Comment by srdee** [comment]
But all the students are getting error messages when they go to retrieve it with the cts typeahead....

**Comment by srdee** [comment]
(And I only just now made it EpiDoc compliant in canonical)

**Comment by srdee** [comment]
Oh wait but I don't get errors when I try in Perseids! Nvm I'll figure this out.

**Comment by balmas** [comment]
ah, I see a couple of lines that might produce errors 137a and 403a... I will fix that.

**Comment by srdee** [comment]
It's breaking somewhere between line 2-3 and line 360-362 -- the former loads and the latter says that the passage doesn't exist

**Comment by srdee** [comment]
The <gap>s that I just fixed in my local copy? Let me know when you've got it--there's a bunch of students here in the Gathering Room trying to start treebanking!

**Comment by srdee** [comment]
(that floating "s" was supposed to be the gap elements

**Comment by balmas** [comment]
it was lines 137a and 403a ... these are fixed now.

not sure about the floating s...

**Comment by balmas** [comment]
oh wait, just saw your comment about 360-362 .. give me a second

**Comment by srdee** [comment]
standing by!

**Comment by balmas** [comment]
ok, the sp tags were perhaps causing a problem?  I've updated the text inventory to have the same fix as for the iliad, looking for //l in the xpath ... let me know if it's working for you now

**Comment by srdee** [comment]
It's working now!

**Comment by srdee** [comment]
Thanks a million!
