### ISSUE TITLE
wrong identifier for 1999.02.0026 (phi0914.phi0012.perseus-eng3 vs phi0914.phi001.perseus-eng3)

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical#144]
According to the text migration list, this should be on GitHub. Am I missing something?

[edit: I did do a content search on my local GitHub repo but the text didn't appear for some reason]

**Comment by lcerrato** [comment]
I was looking at http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0026%3Abook%3D2%3Achapter%3D62
which indicated this is 
urn:cts:latinLit:phi0914.phi0012.perseus-eng3
so when you go to
https://github.com/PerseusDL/canonical/tree/master/CTS_XML_TEI/perseus/latinLit/phi0914/phi0012
there is no perseus-eng3

this can be found in phi0914.phi001

**Comment by lcerrato** [comment]
this may be a cataloging issue; will follow up

**Comment by balmas** [comment]
The problem with P4 originates with the urn entered in the classics.xml. I think the Livy probably all needs review, I'm not sure.

**Comment by lcerrato** [comment]
should I redirect to catalog or leave it for now? Livy works are problematic.

**Comment by balmas** [comment]
I honestly don't know...

**Comment by lcerrato** [comment]
will revisit in context of catalog URI assignment
