### ISSUE TITLE
tlg0007.tlg004.perseus-grc1.xml <title> tag

### ISSUE THREAD

**Issue by sonofmun** [PerseusDL/canonical#153]
Line 6 reads:

```
<title n="Lyc." type="sork">Lycurgus</title>
```

`type` should be "work"

**Comment by sonofmun** [comment]
Same with:
tlg0007.tlg005.perseus-grc1.xml
tlg0007.tlg030.perseus-grc1.xml
tlg0007.tlg031.perseus-grc1.xml

**Comment by PonteIneptique** [comment]
Hey @sonofmun , the new repository you should submit issues to is https://github.com/PerseusDL/canonical-greekLit.

**Comment by sonofmun** [comment]
Then I should be pulling and parsing from there too.  Thanks, Thibault.

On 09.07.2015 15:42, Thibault Clérice wrote:

> Hey @sonofmun https://github.com/sonofmun , the new repository you 
> should submit issues to is 
> https://github.com/PerseusDL/canonical-greekLit.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/PerseusDL/canonical/issues/153#issuecomment-119970889.

## 

Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by PonteIneptique** [comment]
You're welcome :) Sorry for the informal tag instead of name. Just easier to be sure you got notified :)
