### ISSUE TITLE
Arabic collection (Lane)

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical#160]
Any suggestions on a good GitHub place for recording user error reports on Lane's lexicon?

**Comment by balmas** [comment]
We should probably put it in https://github.com/PerseusDL/lexica don't you think?

**Comment by lcerrato** [comment]
Is PerseusDL/arabica going to be used?

**Comment by balmas** [comment]
I don't know. I didn't create it ... (or if I did, I have no memory of doing so...)

**Comment by lcerrato** [comment]
!
Ok. I was looking for a canonical-arabicLit but I guess not.
