### ISSUE TITLE
odd characters in Smyth Greek 1999.04.0007

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical#19]
There are Unicode characters in Smyth which were not properly rendered in beta code. Must be visually cross checked and then enter Unicode equivalents somewhere in document (perhaps as comments).

I do not know if these will display in Perseus at this time so this is low priority.

**Comment by lcerrato** [comment]
I tried to note these when they were brought to my attention. There may be lingering patterns in older texts <*> was the old placeholder for characters data entry did not recognize.

**Comment by helmadik** [comment]
Hi,
I've just done some clean up on Smyth and other monographs. The
unrecognized entities I'd taken care of before. Perhaps we can compare
versions this summer.

Helma Dik
Department of Classics
University of Chicago

**Comment by lcerrato** [comment]
Thanks, Helma. Updated this in light of new push towards beta code - unicode cleanup underway so I am pinging old issues I had created that touched on these issues.

**Comment by helmadik** [comment]
OK! Yes my Smyth version is Unicode.

Helma Dik
Department of Classics
University of Chicago

**Comment by lcerrato** [comment]
moved https://github.com/PerseusDL/canonical_pdlrefwk/issues/15
