### ISSUE TITLE
tlg0023.tlg001.perseus-grc1.xml use unregistered entities

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical#79]
In `/CTS_XML_TEI/perseus/greekLit/tlg0023/tlg001/tlg0023.tlg001.perseus-grc1.xml`, when adding the document to latest BaseX, I get the following error

`"perseus-canonical/CTS_XML_TEI/perseus/greekLit/tlg0023/tlg001/tlg0023.tlg001.perseus-grc1.xml" (Line 161): The entity "lpar" was referenced, but not declared.`

**Comment by lcerrato** [comment]
@srdee we can probably close this
